# Generated by Django 4.2.7 on 2023-12-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eth_sig_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='donor',
            new_name='donor_address',
        ),
    ]
