# Generated by Django 4.2.7 on 2023-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth_sig_auth', '0002_rename_donor_proposal_donor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='pairs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
